societes:
  Galec:
    name: SC Galec
    SIREN: 642007991
    VAT: FR36642007991
    address:
      streetName: 26 quai Marcel Boyer
      cityName: IVRY-SUR-SEINE
      postalCode: 94200
      country: FR
  Scafel:
    name: Scafel
    SIREN: 851303982
    VAT: FR25851303982
    address:
      streetName: 26 quai Marcel Boyer
      cityName: IVRY-SUR-SEINE
      postalCode: 94200
      country: FR
  ConsoRegie:
    name: Conso Regie
    SIREN: 823332978
    VAT: FR64823332978
    address:
      streetName: 26 quai Marcel Boyer
      cityName: IVRY-SUR-SEINE
      postalCode: 94200
      country: FR

types:
  facture: 
    name: Invoice
    code: 380
    sign: ""
  avoir: 
    name: CreditNote 
    code: 381
    sign: "-"

vendor:
  name: missing
  SIREN: missing
  VAT: missing
  address:
    streetName: missing
    cityName: missing
    postalCode: missing
    country: FR

payloadOnly: no
headerID: OUT_1111
societe: Galec  # ENUM: voir societes

documentType: facture  # ENUM: voir types

documentInfo:
  number: ''  # champ obligatoire
  issueDate: ''  # champ obligatoire
  dueDate: ''  # champ obligatoire
  notes: []
  currency: EUR
  # code: 380  # surcharge le code automatique défini dans les types

documentReference:
  number: ''      # champ obligatoire en cas d'avoir
  issueDate: ''   # champ obligatoire en cas d'avoir sur facture
  contractDates:
    start: ''     # champ obligatoire en cas d'avoir sur contrat
    end: ''       # champ obligatoire en cas d'avoir sur contrat

PONumber: ''

payment:
  types: 
    VIREMENT: 30
    PRELEVEMENT: 59
  type: VIREMENT  # ENUM: voir types
  IBAN: ''  # champ obligatoire
  termsID: 30N

lineDetails: []
  # - name: "Nom"
  #   quantity: 1
  #   unitprice: 100
  #   vat: 0
  #   note: "Commentaires Défini mutuellement"

VATamount: {}

VAT0:
  code: Z
  # vatexCause: VATEX-EU-O
