societes:
  Galec:
    name: SC GALEC
    SIREN: 642007991
    VAT: FR36642007991
    address:
      streetName: 26 quai Marcel Boyer
      cityName: IVRY-SUR-SEINE
      postalCode: 94200
      country: FR
  Scafel:
    name: SCAFEL
    SIREN: 851303982
    VAT: FR25851303982
    address:
      streetName: 26 quai Marcel Boyer
      cityName: IVRY-SUR-SEINE
      postalCode: 94200
      country: FR
  ConsoRegie:
    name: CONSO REGIE
    SIREN: 823332978
    VAT: FR64823332978
    address:
      streetName: 26 quai Marcel Boyer
      cityName: IVRY-SUR-SEINE
      postalCode: 94200
      country: FR

vendor:
  name: missing
  SIREN: missing
  VAT: missing
  address:
    streetName: missing
    cityName: missing
    postalCode: missing
    country: FR

payloadOnly: no
headerID: OUT_1111
societe: Galec  # ENUM: voir societes

invoice:
  number: missing
  issueDate: missing
  dueDate: missing
  notes: []
  currency: EUR

PONumber: ""

payment:
  types: 
    VIREMENT: 30
    PRELEVEMENT: 59
  type: VIREMENT  # ENUM: voir types
  IBAN: FR761111111111111111
  termsID: 30N

invoiceLines: []

VATamount: {}